### ISSUE TITLE
Parser issues

### ISSUE THREAD

**Issue by sndth** [fktn-k/fkYAML#449]
### Description

I found some potential parser issues. First, when we use this YAML:
```yaml
1:
1
```
Shouldn't we get an error like:
```
Map keys must be unique at line 1, column 3
Implicit map keys need to be followed by map values at line 2, column 1
```
at least, these errors appear on websites like https://www.yamllint.com or https://jsonformatter.org/yaml-validator. However, when we parse the document using the library, it will not return any messages.

The second issue is related to the key-value section. When we use this YAML:
```yaml
abc def
```
or this:
```yaml
abc:
  def ghi
```
everything works fine. But when we use:
```yaml
abc:
  def: ghi
  jkl mno
```
Websites show the following error: `Implicit map keys need to be followed by map values at line 3, column 3`, while the library parses the document without any problem.

### Reproduction steps

Just like in the description.

### Expected vs. actual results

Library should (probably) throw exceptions, but it doesn't throw anything.

### Minimal code example

```cpp
#include <fstream>

#include "node.hpp"

int
main()
{
  try {
    std::ifstream ifs("test.yaml");
    fkyaml::node yaml = fkyaml::node::deserialize(ifs);
  } catch (fkyaml::exception& e) {
    std::cout << e.what();
  }
}
```

### Compiler and operating system

MSVC (v143, Windows 10)

### Library version

develop (latest)

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/fktn-k/fkYAML/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/fktn-k/fkYAML#how-to-execute-the-unit-tests).

**Comment by fktn-k** [comment]
@sndth   
Thanks for filing the issue! I've confirmed the wrong behaviors.  
Both of them seem to be due to a missing check for a following ":" mapping value indicator.  
They should be treated as errors since at least the ":" mapping value indicator must appear after a mapping key to generate a valid mapping (mapping value can be omitted).  
I'll try to fix it!

**Comment by fktn-k** [comment]
@sndth   
The reported issues should be resolved by the pull request #450.  
An appropriate error is now emitted against a YAML document like the ones shared above.  
Could you confirm the fix with the develop HEAD?

**Comment by sndth** [comment]
Hello, thank you for your fix so much! Unfortunately, it only partially solved the issue. When we try to pass the following code to the parser:
```yaml
abc:
  def ghi
  jkl: mno
```
it should throw an error like (https://jsonformatter.org/yaml-validator):
```
Error : bad indentation of a mapping entry at line 3, column 6:
      jkl: mno
         ^
Line : undefined  undefined
```
but it doesn't throw any problem.

**Comment by fktn-k** [comment]
@sndth   
The reported issue should be resolved by the PR #451.  
It's also fixed a related issue in detecting bad indentations for block sequence entries as well.  
Could you confirm the fix again?

**Comment by sndth** [comment]
> @sndth The reported issue should be resolved by the PR #451. It's also fixed a related issue in detecting bad indentations for block sequence entries as well. Could you confirm the fix again?

Hi! I can, fix works like a charm, thank you!
